### ISSUE TITLE
Create Bootstrap Documentation under 03_Frontend

### ISSUE THREAD

**Issue by dro42** [SAMJ-CSDC26BB/SAMJ-Django-TBC#26]
@SergiuCl please create a page or link some guides/documentation regarding bootstrap as the rest of us has no experience. 

Here: https://github.com/SAMJ-CSDC26BB/SAMJ-Django-TBC/wiki/03_Frontend

**Comment by SergiuCl** [comment]
Done:
* documentation for frontend part
